### ISSUE TITLE
ESB: Add React file as email template

### ISSUE THREAD

**Issue by igorfelipeduca** [sigcoding/building-blocks#2]
## ESB: React file as email template

Our Email Sending Block (ESB) needs to be able to send React files as email template.

At this moment, we just can send html files as email template, as you can see at our `src/index.ts` file.

### Tasks
- [ ] Add React and .tsx support
- [ ] Make tsconfig recognize .tsx files
- [ ] Create a React email template
- [ ] Send email template
- [ ] Write integration tests  

See: https://react.email/docs/integrations/resend
